In [30]:
import pandas as pd
import numpy as np
df_data=pd.read_csv(r"D:\Mobadra\Preprocessing\googleplaystore.csv")
df_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [19]:
df_data.copy()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [32]:
df_data.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [34]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [36]:
df_data.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [38]:
df_data.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [40]:
df_data["Last Updated"] = pd.to_datetime(df_data["Last Updated"], errors="coerce")
print(df_data.dtypes)

App                       object
Category                  object
Rating                   float64
Reviews                   object
Size                      object
Installs                  object
Type                      object
Price                     object
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver               object
dtype: object

In [42]:
df_data['Rating']=df_data['Rating'].fillna(df_data['Rating'].mean())
print(df_data['Rating'])
df_data.isna().sum()

0        4.100000
1        3.900000
2        4.700000
3        4.500000
4        4.300000
           ...
10836    4.500000
10837    5.000000
10838    4.193338
10839    4.500000
10840    4.500000
Name: Rating, Length: 10841, dtype: float64

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      1
Current Ver       8
Android Ver       3
dtype: int64

In [201]:
import pandas as pd
import numpy as np
df_data=pd.read_csv(r"D:\Mobadra\Preprocessing\googleplaystore.csv")

def convert_to_kb(Size):
    if 'M' in Size:
        return float(Size.replace('M',' ')) 
    elif 'k' in Size:
        return float(Size.replace('k',''))
    else:
        return None
df_data['Updated_Size'] = df_data['Size'].apply(convert_to_kb)
df_data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Updated_Size
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,53.0
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,3.6
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,9.5
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,NaN
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,19.0

In [44]:
df_data.dtypes

App                       object
Category                  object
Rating                   float64
Reviews                   object
Size                      object
Installs                  object
Type                      object
Price                     object
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver               object
dtype: object

In [46]:
df_data['Last Updated'] = pd.to_datetime(df_data['Last Updated'], errors='coerce')
df_data.dtypes

App                       object
Category                  object
Rating                   float64
Reviews                   object
Size                      object
Installs                  object
Type                      object
Price                     object
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver               object
dtype: object

In [217]:
def convert_price(Price):
    if pd.isna(Price):  
        return None  
    if isinstance(Price, str) and '$' in Price:  
        return float(Price.replace('$', ''))
    if isinstance(Price, (int, float)):  
        return float(Price)
    return None  
df_data['New_price'] = df_data['Price'].apply(convert_price)
print(df_data['New_price'].isna().sum())
df_data['New_price'] = df_data['New_price'].fillna(0)
print([df_data['New_price'].isna()])

10041
[0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: New_price, Length: 10841, dtype: bool]

In [50]:
df_data['New_price'].sample(10)

9371    0.00
9292    0.00
1518    0.00
8724    4.99
4588    0.00
1357    0.00
111     0.00
854     3.99
7097    4.99
2790    0.00
Name: New_price, dtype: float64

In [52]:
# df_data['Type'].unique()
# df_data['Type'].isnull().sum()
df_data['Type']=df_data['Type'].fillna("free")
df_data['Type'].isnull().sum()
df_data.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    1
Genres            0
Last Updated      1
Current Ver       8
Android Ver       3
New_price         0
dtype: int64

In [54]:
df_data['Content Rating'].value_counts()
df_data['Content Rating']=df_data['Content Rating'].fillna("Everyone")

df_data.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      1
Current Ver       8
Android Ver       3
New_price         0
dtype: int64

In [56]:
df_data['Current Ver']=df_data['Current Ver'].fillna("Varies with device")
df_data.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      1
Current Ver       0
Android Ver       3
New_price         0
dtype: int64

In [58]:
df_data['Android Ver'].value_counts()
df_data['Android Ver']=df_data['Android Ver'].fillna("4.1 and up")
df_data.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      1
Current Ver       0
Android Ver       0
New_price         0
dtype: int64

In [60]:
df_data.dtypes

App                       object
Category                  object
Rating                   float64
Reviews                   object
Size                      object
Installs                  object
Type                      object
Price                     object
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver               object
New_price                float64
dtype: object

In [62]:
most_expensive_app = df_data[df_data['New_price'] == df_data['New_price'].max()]
print(most_expensive_app[['App', 'New_price']])

                           App  New_price
4367  I'm Rich - Trump Edition      400.0

In [64]:
genre_counts = df_data['Category'].value_counts()
most_common_genre = genre_counts.idxmax()
most_common_count = genre_counts.max()

print(f"{most_common_genre}' with {most_common_count} apps.")

FAMILY' with 1972 apps.

In [274]:
free_apps = df_data[df_data['New_price'] == 0]
paid_apps = df_data[df_data['New_price'] > 0]
avg_size_free = free_apps['Updated_Size'].mean()
avg_size_paid = paid_apps['Updated_Size'].mean()

print(f"Average size of free apps: {avg_size_free:.2f} MB")
print(f"Average size of paid apps: {avg_size_paid:.2f} MB")

Average size of free apps: 35.17 MB
Average size of paid apps: 58.78 MB

In [93]:
perfect_rated_apps = df_data[df_data['Rating']==5]
most_expensivet_apps = perfect_rated_apps.sort_values(by='New_price', ascending=False).head(5)

print(most_expensivet_apps[['App','Rating','New_price']])

                                            App  Rating  New_price
5489                  AP Art History Flashcards     5.0      29.99
7477                 USMLE Step 2 CK Flashcards     5.0      19.99
5246                      Hey AJ! It's Bedtime!     5.0       4.99
7204  TI-84 CE Graphing Calculator Manual TI 84     5.0       4.99
5482                 meStudying: AP English Lit     5.0       4.99

In [280]:
num_apps = df_data[df_data['Reviews'] > 50000].shape[0]

print(f"Number of apps with more than 50K reviews: {num_apps}")

Number of apps with more than 50K reviews: 2782

In [153]:
df_data['Installs'] = df_data['Installs'].str.replace('[+,]','',regex=True).astype(float)
avg_price = df_data.groupby(['Category', 'Installs'])['New_price'].mean().reset_index()
avg_price.head(10)

         Category  Installs  New_price
0             1.9      Free   0.000000
1  ART_AND_DESIGN         0   0.000000
2  ART_AND_DESIGN       100   0.000000
3  ART_AND_DESIGN      1000   0.663333
4  ART_AND_DESIGN     10000   0.180909
5  ART_AND_DESIGN    100000   0.000000
6  ART_AND_DESIGN   1000000   0.000000
7  ART_AND_DESIGN  10000000   0.000000
8  ART_AND_DESIGN      5000   0.398000
9  ART_AND_DESIGN     50000   0.000000

In [175]:
high_rating_apps = df_data[df_data['Rating'] > 4.7]
num_of_rating_apps = high_rating_apps['Rating'].shape[0]
avg_of_rating_apps = high_rating_apps['New_price'].mean()
print(f"number of high ratinhgapps is: {num_of_rating_apps}")
print(f"average of high rating apps is: {avg_of_rating_apps:.2f}")

number of high ratinhgapps is: 596
average of high rating apps is: 0.50

In [ ]:
df_data['Installs'] = df_data['Installs'].str.replace('[+,]','',regex=True)
df_data['Installs'] = df_data['Installs'].replace('Free',np.nan)
df_data['Installs'].value_counts()

In [191]:
df_data['Installs'] = df_data['Installs'].str.replace('[+,]','',regex=True).astype(float)
High_install_apps = df_data[df_data['Installs'] >= 5000000]
app_sales = (df_data['Installs'] * High_install_apps['New_price']).sum()
google_revenue = app_sales * 0.30
print(f"Google's 30% cut is: {google_revenue:.2f}")

Google's 30% cut is: 44910000.00

In [230]:
df_data['Updated_Size'] = pd.to_numeric(df_data['Updated_Size'], errors='coerce')
df_data['App_Type'] = df_data['New_price'].apply(lambda x: 'Paid' if x > 0 else 'Free')
size_stats = df_data.groupby('App_Type')['Updated_Size'].agg(['min', 'max'])
size_stats

          min     max
App_Type
Free      1.0   994.0
Paid      1.0  1020.0

In [248]:
correlation_columns = ['Rating', 'Reviews', 'Updated_Size', 'New_price']
correlation_matrix = df_data[correlation_columns].corr()
correlation_matrix

                Rating   Reviews  Updated_Size  New_price
Rating        1.000000  0.068141     -0.018843  -0.021176
Reviews       0.068141  1.000000      0.032105  -0.009667
Updated_Size -0.018843  0.032105      1.000000   0.014495
New_price    -0.021176 -0.009667      0.014495   1.000000

In [268]:
df_data['New_price'] = pd.to_numeric(df_data['New_price'], errors='coerce')
df_data['App_Type'] = df_data['New_price'].apply(lambda x: 'Paid' if x > 0 else 'Free')
app_counts = df_data.groupby(['Content Rating', 'App_Type']).size().unstack()
app_counts

App_Type           Free   Paid
Content Rating
Adults only 18+     3.0    NaN
Everyone         8019.0  695.0
Everyone 10+      381.0   33.0
Mature 17+        479.0   20.0
Teen             1156.0   52.0
Unrated             2.0    NaN

In [278]:
android_4x_apps = df_data[df_data['Android Ver'].str.startswith('4.', na=False)]
print(f"Number of apps compatible with Android version 4.x: {android_4x_apps.shape[0]}")

Number of apps compatible with Android version 4.x: 6959